# Generated by Django 5.1.6 on 2025-02-23 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthconnect', '0002_rename_age_diagnosismodel_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorsmodel',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='doctorsmodel',
            name='qualifications',
        ),
    ]
