# Generated by Django 5.1.6 on 2025-02-23 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthconnect', '0004_remove_doctorrecommendation_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorsmodel',
            name='profile_picture',
        ),
    ]
