# Generated by Django 5.1.6 on 2025-02-23 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthconnect', '0005_remove_doctorsmodel_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_recommendation', to=settings.AUTH_USER_MODEL),
        ),
    ]
