# Generated by Django 5.1.6 on 2025-02-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthconnect', '0006_alter_doctorrecommendation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsmodel',
            name='short_Bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
