# Generated by Django 5.1.6 on 2025-02-23 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthconnect', '0008_remove_diagnosismodel_test_result_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosismodel',
            name='full_name',
        ),
    ]
